
name: Deploy CodeCraft AI to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build CodeCraft AI
        run: npm run build
        env:
          NODE_ENV: production
          # Add cache busting by using the commit hash
          VITE_CACHE_BUSTER: ${{ github.sha }}
        
      # Create 404.html for SPA routing
      - name: Create 404.html
        run: |
          cat > ./dist/404.html << 'EOL'
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>CodeCraft AI - Page Not Found</title>
              <script type="text/javascript">
                var pathSegmentsToKeep = 1;
                var l = window.location;
                l.replace(
                  l.protocol + '//' + l.hostname + (l.port ? ':' + l.port : '') +
                  l.pathname.split('/').slice(0, 1 + pathSegmentsToKeep).join('/') + '/?/' +
                  l.pathname.split('/').slice(1 + pathSegmentsToKeep).join('/').replace(/&/g, '~and~') +
                  (l.search ? '&' + l.search.slice(1).replace(/&/g, '~and~') : '') +
                  l.hash
                );
              </script>
            </head>
            <body>
              <div style="text-align: center; padding: 50px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">
                <h2 style="color: #667eea;">Redirecting to CodeCraft AI...</h2>
                <p style="color: #666;">Please wait while we redirect you to the correct page.</p>
                <div style="width: 40px; height: 40px; border: 4px solid rgba(102,126,234,0.3); border-top: 4px solid #667eea; border-radius: 50%; animation: spin 1s linear infinite; margin: 20px auto;"></div>
                <style>
                  @keyframes spin {
                    0% { transform: rotate(0deg); }
                    100% { transform: rotate(360deg); }
                  }
                </style>
              </div>
            </body>
          </html>
          EOL
      
      # Update index.html for SPA routing
      - name: Update index.html for SPA
        run: |
          sed -i '/<head>/a \
          <!-- Start Single Page Apps for GitHub Pages --> \
          <script type="text/javascript"> \
            (function(l) { \
              if (l.search[1] === "/" ) { \
                var decoded = l.search.slice(1).split("&").map(function(s) { \
                  return s.replace(/~and~/g, "&"); \
                }).join("?"); \
                window.history.replaceState(null, null, \
                    l.pathname.slice(0, -1) + decoded + l.hash \
                ); \
              } \
            }(window.location)) \
          </script> \
          <!-- End Single Page Apps for GitHub Pages -->' ./dist/index.html
      
      # Create a .nojekyll file to prevent Jekyll processing
      - name: Create .nojekyll file
        run: touch ./dist/.nojekyll
        
      # Deploy to GitHub Pages
      - name: Deploy CodeCraft AI to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy to
          branch: gh-pages # The branch the action should deploy to
          clean: true # Automatically remove deleted files from the deploy branch
          force: true # Force update even if remote history differs
